### ISSUE TITLE
Milestone 7: Getting a full brained high resolution nuclear image 

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#10]
Problems:
- Personnel issues: hiring a new postdoc 
- Other labs will feed their brain data (same microscope, different types of mouse) - will be able to tissue clear 10 brains simultaneously

**Comment by KCB13** [comment]
Update from slack message on August 28th, @jasonlouisstein stated: Oleh Krupa, my grad student who is making great progress on the tissue clearing, added a 30 GB image up into BrainI which is a full brain slice stained with DRAQ5 (a nuclear marker).  One of the problems from this is that the field of view of the microscope is small so many images need to be stitched together.  The stitching is difficult problem because the brain is slowly increasing in size while sitting in the medium during the imaging period.  This is going to be another problem to tackle especially for whole brains.

**Comment by KCB13** [comment]
@jasonlouisstein has this been accomplished?

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
