### ISSUE TITLE
Onboarding New Investigators/Collaborators to BRAIN-I

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#11]
@jasonlouisstein @michael-conway Ashok wants to know what the process will look like for introducing new investigators to BRAIN-I including how new investigators will be trained to use the metadata templates for data ingestion. 

- [ ] @michael-conway Ashok requests that you create a powerpoint presentation specifically geared towards training new investigators on how to use the metadata templates. He would like the opportunity to review this presentation. Could you have this ready by our July 14 call? 

- [ ] @jasonlouisstein & @michael-conway Ashok suggests creating formal documentation to describe: 
- how to onboard new investigators (i.e. what do they need to be a part of BRAIN)
- training need to have in order to begin data ingestion 
- what they need to use the DE 

Milestones: #2 #9

**Comment by KCB13** [comment]
From July28 biweekly call:
- is really dependent on #7 and will not be ready to be updated until #7 is completed

**Comment by KCB13** [comment]
From September 8 Biweekly call and recent slack messages:

- @jasonlouisstein presented BRAIN-I on September 7th, link to presentation: https://www.dropbox.com/s/d7eplu9q05zdatt/Stein_BRAINi.pptx?dl=0
- From September 7th slack message @jasonlouisstein stated: also Ashok lot of interest in using the infrastructure after the talk, people also intersted in similar type of infrastructure for MRI image sharing (Ian Shih) and calcium imaging sharing (Garret Stuber) so basically you could get a lot of instances of useage for xDCI for BRAINi specifically, we can get at least 4 groups signing on, but first it is essential that we get the upload tool and clearmap and guorong's code up and running within BRAINi once that works, we can get at least 4, probably way more at UNC, and then we can go to Duke and NC-state as well
- As a result of the success of the presentation in generating new investigators, I labeled issue #7 as critical path in order to onboard new investigators

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
