### ISSUE TITLE
Build BRAIN-I iRODS Infrastructure 

### ISSUE THREAD

**Issue by jonc1438** [ResearchSoftwareInstitute/BRAIN-I#17]
Load iRODS Resource Server on Neuro GPU server "DONE"
Aquire VM at RENCI and load iRODS Resource Server for RENCI replication node
Create iRODS Federation between new NeuroResource on GPU Machine and RENCI replication node

Milestone: #2

**Comment by KCB13** [comment]
From 12/4 Email

The permanent iRODS PC came in, then OIS wanted to move it to their DMZ, and each change started the registration process over.

Current status is we're waiting for OIS to submit the client access rules to Information Security, but JT is understandably holding off until the security scanner can scan the machine, which is campus policy. He's got another ticket in with information security to get an RSA key for SoM so scans will work.

**Comment by donsizemore** [comment]
We got our firewall rules from OIS/InfoSec on Monday afternoon, Dec 11. We can now connect clients and I have acPostProcForPut firing an irsync from Neuro to RENCI. We've got a config mismatch between the RENCI iRODS host and the Research Computing iRODS consumer server - I'm meeting Bill Schulz this afternoon to iron that out.

**Comment by donsizemore** [comment]
This is by and large done, barring any further reconfiguration needed for HydroShare.

I still need to catch up with Bill Schulz to figure out why steindb.its.unc.edu in Research Computing can't federate with braini-rods.renci.org, but everything else is talking.

**Comment by KCB13** [comment]
Closing to make way for new action items and issues. Will reopen if needed.
