### ISSUE TITLE
Test Hydroshare App Store Build for BRAIN-I using ImageJ

### ISSUE THREAD

**Issue by jonc1438** [ResearchSoftwareInstitute/BRAIN-I#18]
- [x] Load test environment at Odum with local generic hydroshare and http://www.tethysplatform.org
- [ ] Build a few test Apps
- [ ] Investigate ImageJ
- [ ] Build wrapper app in Odum App Store for ImageJ
- [ ] Replicate in RENCI infrastructure when finalized for review

Milestone: #3

**Comment by KCB13** [comment]
From 11/3/17 BiWeekly BRAIN-I Call: 
Action item: Install ImageJ on GPU computer and mount iRODS

**Comment by KCB13** [comment]
From 11/03/17 Biweekly BRAIN-I Call: 
- [ ] Install ImageJ on GPU computer and mount iRODS

**Comment by KCB13** [comment]
Closing to make way for new action items and issues. Will reopen if needed.
