### ISSUE TITLE
Milestone 1: Refine upload process from microscope to BRAIN-I

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#2]
@jasonlouisstein's comments: Mike's got a very good start on that and we used it to upload some test images from the microscope computer onto the grid.  It needs refinement and as we use it we will give feedback as to how it can be refined and improved.

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
