### ISSUE TITLE
Complete implementation of pre-processing tools outside of BRAIN-I

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#20]
This is an action item from the July, 17th, 2018 BRAIN-I F2F.

To be assigned: Murali (assigning Ray for now)
Will require input from: @erikscott and Oleh

Report back on status during the August 3rd BRAIN-I Call.

NOTE: This is a stop gap measure for now - ideally, eventually the pre-processing tools will be incorporated into BRAIN-I.

**Comment by KCB13** [comment]
![img_0304](https://user-images.githubusercontent.com/18745397/42958929-0b5adc70-8b55-11e8-9f5d-682f2a2a22db.jpg)

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
