### ISSUE TITLE
Refactor metadata template to incorporate the metadata templates and landing zone features into iRODS

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#21]
This is an action item from the July, 17th, 2018 BRAIN-I F2F.

To be assigned: Bhai and Raja (to be added into the BRAIN-I Github)

Report back on status during the August 3rd BRAIN-I Call.

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
