### ISSUE TITLE
Investigate VNC dockerization of both ImageJ and MATLAB 

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#23]
Note: these tools for now, hopefully will look into python code, etc 

This is an action item from the July, 17th, 2018 BRAIN-I F2F.

To be assigned: Murali (assigning Ray for now)

Report back on status during the August 3rd BRAIN-I Call.

**Comment by KCB13** [comment]
@kcb13 and @rayi113 to follow up re: ImageJ.

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
