### ISSUE TITLE
Getting Jack Snoeyink access to the data

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#25]
This is an action item from the July, 17th, 2018 BRAIN-I F2F.

- [x] Ashok to follow up with Guorong 

Report back on status during the August 3rd BRAIN-I Call.

Context: 

The cell nuclei identification data seems like a perfect fit for an undergraduate who wants to compare topological data analysis (TDA) with convolutional neural nets (CNN).  Math and CS major SiYang Jing did well in my algorithms (comp 550) class last semester, and we’ve been talking about what data set and methods to use for an undergraduate thesis that might combine TDA and machine learning.  So please bring this up tomorrow, and add me (and siyangj@live.unc.edu, if you don’t mind) to the Friday zoom meeting.

**Comment by ashokohio** [comment]
Exchanged emails with Guorong, he is traveling. Will catch up on Monday, 7/23.

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
