### ISSUE TITLE
NVIDIA Grid Server 

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#26]
- [ ] Move to NVIDIA grid server @rayi113 
- [ ] Will School of Medicine object if we can bring this grid into Jason’s lab (Jason?); space proximity cooling, don’t have cooling, needs to be it’s own box @jasonlouisstein 

This is an action item from the July, 17th, 2018 BRAIN-I F2F.

Report back on status during the August 3rd BRAIN-I Call.

**Comment by KCB13** [comment]
Ray, Jason, and Oleh have been discussing quotes, see email chain titled "Re: Doodle Poll: BRAIN-I F2F Meeting at RENCI"

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
