### ISSUE TITLE
Milestone 2: Improve the process to share images and code

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#3]
@jasonlouisstein's comments: This seems to be native in iRODS/DE, but it would be great if we can make this just a little more user friendly.  There are a lot of clicks to get to where we need to be.  It seems that we always end up with a ton of windows open in DE after trying to do anything.  The skin would really benefit from some improvement.

**Comment by KCB13** [comment]
Do we want to have a dedicated workflow working face webpage - hard to change how iRODS/DE looks. 
Prioritizing apps to add/quality control first. Will revisit. 
Maybe in the grant - discuss how we will make it more user friendly.

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
