### ISSUE TITLE
Sync HeLx and BRAIN-I one more time

### ISSUE THREAD

**Issue by bryttanytodd** [ResearchSoftwareInstitute/BRAIN-I#30]
Then BRAIN-I will be able to onboard users.

**Comment by hyi** [comment]
@bryttanytodd @rayi113 braini.commonsshare.org has been rebuild with latest CommonsShare codebase. Please test it out and see if it works well for user onboarding.

**Comment by rayi113** [comment]
@hyi The following didn't work just now: I tried drag-and-dropping a small pdf file to create a new resource and it hangs indefinitely with the hourglass cursor.

**Comment by hyi** [comment]
@rayi113 that is ACL issue in iRODS. I will delete your test resource and reset ACL properly in iRODS and then ask you to test again.

**Comment by hyi** [comment]
@rayi113 It appears to all work now based on my testing. See if everything works for you as well.

**Comment by rayi113** [comment]
@hyi Yes, works now, closing issue, thanks.
