### ISSUE TITLE
Milestone 3: Implementation of a pipeline executing ClearMap

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#4]
@jasonlouisstein's comments: The code can be downloaded from above and we need to wrap it up and put it as a pipeline, where we can quality check each stage.  I'm not really sure how this works, I get how to make individual programs to execute but I don't get how to make them run one by one on the data.  Again, quality checking is essential, so this needs to be a consistent part of every pipeline.

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
