### ISSUE TITLE
Milestone 4: Implement Guorong's code on GPU

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#5]
@jasonlouisstein's comments: As Guorong's code develops, and I imagine there will be many iterations, we'll need to put that onto BRAINi so as to compare to ClearMap and demonstrate it's superiority!

**Comment by KCB13** [comment]
@erikscott what is the status of implementing the GPU code?

**Comment by rayi113** [comment]
Closing old Brain-I GitHub repo issues so team can start anew.
