### ISSUE TITLE
Metadata Prep load tool

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#7]
- Update metadata templates in the iRODS tool
- Fix directory structure to associate the right channel with the dye 

@jasonlouisstein @michael-conway to meet Friday, June 23
Goal: Have it done by early next week (week of June 26-30)

Milestone: #2

**Comment by KCB13** [comment]
From July14 BRAIN-I Biweekly Call: 
- Version 2 of the metadata template is ready to test
- Mike and Jason to meet either July 20 or July 21 to test. @michael-conway @jasonlouisstein please update this issue after meeting with how testing of version 2 goes.

**Comment by KCB13** [comment]
From July28 BRAIN-I Biweekly Call:

- Got derailed for the NIH Data Commons grant @michael-conway to schedule some microscope time during the week of July31 
- Main tasks are iterating through the metadata data and to start pushing data

**Comment by KCB13** [comment]
From September 8 BRAIN-I Biweekly Call and recent slack messages:

- @michael-conway identified next steps to improve, which include tweaks to validation, some work to text completion, etc. 
- Continuing to iterate through prep load tool 
- From a slack message on August 28th: @jasonlouisstein stated: oleh says it took 10-15mins for 40GB upload using the tool, hopefully we can decrease that by uploading direct to ITS instead of direct to RENCI?
- From a slack message on September 12th: @jasonlouisstein asked @michael-conway: can you add the upload tool to the lightsheet microscopy core microscope?  It is run by Pablo Ariel

**Comment by jonc1438** [comment]
Design of workflow still under investigation in light of new infrastructure changes. Current ETA is for clear development direction and potential prototype

**Comment by jonc1438** [comment]
After testing the new iDROP client on the Win7 PC in the lab we have discovered a new issue that is presenting a challenge. The current workflow involves storing the images on a Med School NetApp share and NOT the local PC Hard drive. iDROP works great from local drive but chokes when accessing data from that SMB share. We have initiated a conversation with the Med School folks managing the NetApps and setting up a test to find the correct solution. This could have been the initial problem moving files to RENCI iRODS and not the wide area link. We are looking into both the iDROP code as well as network issues.

**Comment by erikscott** [comment]
Just a hunch – spaces in the path/filename? Otherwise it would have to be permissions, or maybe forward versus backslashes? That last idea is chasing ghosts, yes.

Erik

**Comment by jonc1438** [comment]
Our first thought was slashes issues too. But they seem are same on local disk and work fine. I like ghosts too. I am leaning toward timing out calculating check sum and locking the upload queue for my ghost hunt.

**Comment by donsizemore** [comment]
Erik, the mounted path did indeed contain spaces: S:\Stein Lab, S:\Smith Lab, etc. I can ping Oleh in Slack and have him test this (or I can head back down tomorrow). As Jon says, iDrop worked fine once we copied a file from the NetApp to local disk.

**Comment by donsizemore** [comment]
@jonc1438 @erikscott @akio-sone I just successfully uploaded a test file from a desktop folder named "path with spaces" with no problem. I traipsed around until I found a NetApp SMB share I could read, mapped the folder as a network drive, and reproduced the behavior we saw in iDrop uploading from the NRC NetApp earlier today.

This may be a bad test as a) the share name indeed contains a space, and b) the folder is read-only to me (it's a world-readable share) so if iDrop is trying to write any temporary checksum data alongside the file that would fail.

When I attempted to eject the network drive Windows cautioned that I still had files open on the share, so iDrop at least opened the file for reading.

**Comment by donsizemore** [comment]
@jonc1438 @erikscott @akio-sone I lied; the read-only path I tried does NOT contain a space, so the read-only permissions should be the only difference. I remember seeing an option to disable checksums on upload in one of the iDrop property files today, but even as a work-around that sounds like something we don't want to disable.

**Comment by KCB13** [comment]
From 11/3/17 BiWeekly BRAIN-I Call - the metadata prep load tool is up and functional. Next, users (like @jasonlouisstein and Oleh Krupa) to test the load tool. Removing Critical Path label.

**Comment by KCB13** [comment]
Closing to make way for new action items and issues. Will reopen if needed.
