### ISSUE TITLE
Python tools (ClearMap) to dockerize 

### ISSUE THREAD

**Issue by KCB13** [ResearchSoftwareInstitute/BRAIN-I#8]
- ClearMap is a pipeline for analyzing these 3D images (not developed at UNC), and want to be able to implement other people's tools so that we can compare to Guorong's GPU code
- Documentation of how to dockerize different tools/applications for future users to access (@erikscott)

Milestone: #3 #4

**Comment by KCB13** [comment]
From September 8 BRAIN-I Call and recent slack messages:

- from a slack message on August 28th @erikscott stated: We have Guorong's code running, just not from DE. Oddly, I started working on making it work from DE about an hour ago, actually. Probably still a few days' work. 
- from the biweekly call: Erik's version of the code is approximately 1 month old, and Guorong has a new version of the code. @erikscott to implement latest version of Guorong's code

**Comment by KCB13** [comment]
From September 18 slack message

 - @jasonlouisstein stated: clearmap is a pipeline for analyzing tissue cleared images, the only publicly available one: https://idisco.info/clearmap-2/ ...We really need to push it to get members actually signed up... We need to make it functional within xDCI so that users can upload data and process it through clearmap If we are to show users signing up for this system in time for the grant application then we need to have this done now...
- ClearMap is the software implementation of our analysis workflow for 3D datasets obtained with iDISCO+. ClearMap is a Python code that interfaces with various open-source softwares to streamline and automate the following tasks: 3D object detection: as of today, 2 detections modes are available. The Spotdetection mode is a high speed detection of spherical objects, such as cell nuclei. The Ilastik mode interfaces with the learning filters trained with Ilastik. 
- Due to this comment, I am labeling this issue as Critical Path for #11

**Comment by KCB13** [comment]
From October 20 slack message (and email to Guorong):

Making progress on ClearMap. Three questions for those with ClearMap experience or who know people who use it:

ClearMap says if we "wish to use machine learning filters" then we need to download "ilastik".  ilastik in turn claims that "[f]or some workflows in ilastik, installation of a commercial solver is required". We can use either IBM's CPLEX or Gurobi's GUROBI. Gurobi has an academic license, as does IBM's CPLEX. 

The "wish to use machine learning filters" is a question for biology-type people, I presume - isn't that what the custom CS department GPU code does? So we perhaps need exactly that. Once that is answered, the follow-on questions are "does your workflow require a commercial solver", and finally, if so, then "CPLEX versus Gurobi... discuss?"

**Comment by KCB13** [comment]
From October 20 BRAIN-I Biweekly Call: 
@erikscott to: 

- [ ] Get plain vanilla ClearMap to run 
- [ ] Dockerize vanilla ClearMap 
- [ ] Give status update by Tuesday, October, 24  
- [ ] Look at Gurobi and see how restrictive the licensing is

**Comment by erikscott** [comment]
ClearMap now running in Docker and using the GPU.

**Comment by crazyhottommy** [comment]
Hi,
I want to use ClearMap, but had difficulties to run it, can you please share your docker container?

Thanks!
Tommy

**Comment by jasonlouisstein** [comment]
Hi Tommy,

I’m not sure if ClearMap ever was dockerized on BRAINi – Oleh do you know?

Thanks,
Jason

--
Jason L. Stein
Assistant Professor
Department of Genetics & Neuroscience Center
University of North Carolina - Chapel Hill
www.steinlab.org

**Comment by crazyhottommy** [comment]
Thanks Jason. I googled around and found this issue in github.

**Comment by erikscott** [comment]
Yes, ClearMap has been dockerized. The docker image is about 4 gigs if I remember right. The machine it runs on must have a CUDA-capable GPU (NVIDIA) and must have "nvidia-docker" installed - the regular "docker run" command isn't supported. If you want to run it on another machine, you'll need a bare minimum of CUDA 7.5.

Let me know a good email address for you and I can walk you through the process.

Regards,
Erik Scott - escott@renci.org

**Comment by crazyhottommy** [comment]
Thanks! @erikscott 
I will need to run it at Harvard RC HPC. you can reach me at tangming2005@gmail.com and your help is greatly appreciated.

**Comment by erikscott** [comment]
Tommy and I will be working in email between us. Thanks everyone!
